DataStructuresAssignment/Controllers/QueueController.cs
/*IS 403 Data Structures Assignment
    Ross Rosenlof, Trevan Reese, Caden Dortch, Ryan Jenks
    This website shows how three data
    structures - stacks, dictionaries, and queues,
    handle data and output them to a view.-*/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DataStructuresAssignment.Controllers
{
    public class QueueController : Controller
    {
        public static Queue<string> queStruct = new Queue<string>();
        public static int iCounter = 0;

        // GET: Queue
        public ActionResult IndexQueue()
        {
            if (queStruct.Count != 0)
            {
                ViewBag.Output = queStruct;
            }

            return View();
        }

        // Add one
        public ActionResult IndexQueue1()
        {
            queStruct.Enqueue(" Item " + ++iCounter + " ");
            
            return View("IndexQueue");
        }

        // Add huge list
        public ActionResult IndexQueue2()
        {
            for (int x = 0; x < 2000; x++)
            {
                queStruct.Enqueue(" Item " + ++iCounter + " ");
            }

            return View("IndexQueue");
        }

        // Display
        public ActionResult IndexQueue3()
        {
            if (queStruct.Count != 0)
            {
                ViewBag.Output = queStruct;
            }

            return View("IndexQueue");
        }

        // Delete From
        public ActionResult IndexQueue4()
        {
            if (queStruct.Count != 0)
            {
                queStruct.Dequeue();
                iCounter--;
            }

            else
            {
                ViewBag.Error = "Nothing to delete";

                iCounter = 0;
            }

            return View("IndexQueue");
        }

        // Clear
        public ActionResult IndexQueue5()
        {
            queStruct.Clear();

            iCounter = 0;

            return View("IndexQueue");
        }

        // Search
        public ActionResult IndexQueue6()
        {
            Random oRand = new Random();
            int iSearchNum = oRand.Next(1,(iCounter + 1));

            System.Diagnostics.Stopwatch sw = new System.Diagnostics.Stopwatch();

            sw.Start();

            if (queStruct.Contains(" Item " + iSearchNum + " "))
            {
                ViewBag.SearchResults = queStruct.ElementAt(iSearchNum - 1);

            }
            else ViewBag.SearchResults = "Not Found";

            sw.Stop();

            TimeSpan ts = sw.Elapsed;

            ViewBag.StopWatch = ts;

            return View("IndexQueue");
        }

        
    }
}

DataStructuresAssignment/Views/Queue/IndexQueue.cshtml
<!--Queue Index-->
<!--IS 403 Data Structures Assignment
    Ross Rosenlof, Trevan Reese, Caden Dortch, Ryan Jenks
    This website shows how three data
    structures - stacks, dictionaries, and queues,
    handle data and output them to a view.-->
@{
    ViewBag.Title = "IndexQueue";
}

<h2>Queue</h2>
<div class="search-results">
    @if (ViewBag.SearchResults != null)
    {
        <p>The search returned the following result: @ViewBag.SearchResults</p>
        <p>In @ViewBag.StopWatch seconds!</p>
    }
    @if (ViewBag.Error != null)
    {
        <p>@ViewBag.Error</p>
    }
</div>

<div class="vertical-menu column left">
    <a href="@Url.Action("IndexQueue1", "Queue")">1. Add one item to Queue</a>
    <a href="@Url.Action("IndexQueue2", "Queue")">2. Add Huge List of Items to Queue</a>
    <a href="@Url.Action("IndexQueue3", "Queue")">3. Display Queue</a>
    <a href="@Url.Action("IndexQueue4", "Queue")">4. Delete from Queue</a>
    <a href="@Url.Action("IndexQueue5", "Queue")">5. Clear Queue</a>
    <a href="@Url.Action("IndexQueue6", "Queue")">6. Search Queue</a>
    <a href="@Url.Action("Index", "Index")">7. Return to Main Menu</a>
</div>


<div class="display_output column right">

    @if (ViewBag.Output != null)
    {
        <p>
            @foreach (var item in ViewBag.Output)
            {
                @item
            }
        </p>
    }


</div>