DataStructuresAssignment/Controllers/DictionaryController.cs
/*IS 403 Data Structures Assignment
    Ross Rosenlof, Trevan Reese, Caden Dortch, Ryan Jenks
    This website shows how three data
    structures - stacks, dictionaries, and queues,
    handle data and output them to a view.-*/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DataStructuresAssignment.Controllers
{
    public class DictionaryController : Controller
    {
        // Declare public static variables to be used for each method
        public static Dictionary<string, int> dictStruct = new Dictionary<string, int>();
        public static int iCounter = 0;

        // GET: Dictionary
        public ActionResult IndexDictionary() // Displays output to ViewBag, default
        {
            if (dictStruct != null)
            {
                ViewBag.Output = dictStruct;                
            }

            return View();
        }

        public ActionResult IndexDictionary1() // Adds one item to the end of the dictionary
        {
            dictStruct.Add(" Item " + ++iCounter +" - ", iCounter);

            return View("IndexDictionary");
        }

        public ActionResult IndexDictionary2() // Adds 2000 items to the end of the dictionary
        {
            int x = 0;
            while(x < 2000)
            {
                dictStruct.Add(" Item " +  ++iCounter + " - ", iCounter);
                x++;
            }
            
            return View("IndexDictionary");
        }

        public ActionResult IndexDictionary3() // Displays dictionary
        {
            if (dictStruct.Count != 0)
            {
                ViewBag.Output = dictStruct;
            }

            return View("IndexDictionary");
        }

        public ActionResult IndexDictionary4() // Removes last item in the dictionary
        {
            if(dictStruct.ContainsKey(" Item " + iCounter + " - "))
            {
                dictStruct.Remove(" Item " + iCounter + " - ");

                iCounter--;
            }

            else // If there are no items in the dictionary, nothing is deleted
            {
                ViewBag.Error = "Nothing to delete";

                iCounter = 0;
            }
            
            return View("IndexDictionary");
        }

        public ActionResult IndexDictionary5() // Clears contents of the dictionary
        {
            dictStruct.Clear();

            iCounter = 0;

            return View("IndexDictionary");
        }

        public ActionResult IndexDictionary6() // Search
        {
            Random randNum = new Random();
            int iRandKeyIndex = randNum.Next(1, (iCounter+1)); // Generates a random number in the range of the dictionary contents

            System.Diagnostics.Stopwatch sw = new System.Diagnostics.Stopwatch();

            sw.Start();

            if (dictStruct.ContainsKey(" Item " + iRandKeyIndex + " - "))
            {
                ViewBag.SearchResults = dictStruct[" Item " + iRandKeyIndex + " - "];
            }

            sw.Stop();

            TimeSpan ts = sw.Elapsed;

            ViewBag.StopWatch = ts;
            
            return View("IndexDictionary");
        }


    }
}

DataStructuresAssignment/Views/Dictionary/IndexDictionary.cshtml
<!--Dictionary Index-->

<!--IS 403 Data Structures Assignment
    Ross Rosenlof, Trevan Reese, Caden Dortch, Ryan Jenks
    This website shows how three data 
    structures - stacks, dictionaries, and queues, 
    handle data and output them to a view.-->
@{
    ViewBag.Title = "IndexDictionary";
}

<h2>Dictionary</h2>
<div class="search-results">
    @if (ViewBag.SearchResults != null)
    {
        <p>The search returned the following result: @ViewBag.SearchResults</p>
        <p>In @ViewBag.StopWatch seconds!</p>
    }
    @if(ViewBag.Error != null)
    {
        <p>@ViewBag.Error</p>
    }
</div>

<div class="vertical-menu column left">
    <a href="@Url.Action("IndexDictionary1", "Dictionary")">1. Add one time to Dictionary</a>
    <a href="@Url.Action("IndexDictionary2", "Dictionary")">2. Add Huge List of Items to Dictionary</a>
    <a href="@Url.Action("IndexDictionary3", "Dictionary")">3. Display Dictionary</a>
    <a href="@Url.Action("IndexDictionary4", "Dictionary")">4. Delete from Dictionary</a>
    <a href="@Url.Action("IndexDictionary5", "Dictionary")">5. Clear Dictionary</a>
    <a href="@Url.Action("IndexDictionary6", "Dictionary")">6. Search Dictionary</a>
    <a href="@Url.Action("Index", "Index")">7. Return to Main Menu</a>
</div>

<div class="display_output column right">

    @if (ViewBag.Output != null)
    {
        <p>
            @foreach (KeyValuePair<string, int> pair in ViewBag.Output)
            {
                @pair.Key 
                @pair.Value
            }
        </p>
    }


</div>