DataStructuresAssignment/Controllers/StackController.cs
/*IS 403 Data Structures Assignment
    Ross Rosenlof, Trevan Reese, Caden Dortch, Ryan Jenks
    This website shows how three data
    structures - stacks, dictionaries, and queues,
    handle data and output them to a view.-*/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DataStructuresAssignment.Controllers
{
    public class StackController : Controller
    {
        public static Stack<string> stackStruct = new Stack<string>();
        public static int iCounter = 0;

        // GET: Stack
        public ActionResult IndexStack()
        {
            if (stackStruct.Count != 0)
            {
                ViewBag.Output = stackStruct;
            }

            return View();
        }

        // Add one
        public ActionResult IndexStack1()
        {
            stackStruct.Push(" Item " + ++iCounter + " ");
            
            return View("IndexStack");
        }

        // Add huge list
        public ActionResult IndexStack2()
        {
            for (int x = 0; x < 2000; x++)
            {
                stackStruct.Push(" Item " + ++iCounter + " ");
            }

            return View("IndexStack");
        }

        // Display
        public ActionResult IndexStack3()
        {
            if (stackStruct.Count != 0)
            {
                ViewBag.Output = stackStruct;
            }

            return View("IndexStack");
        }

        // Delete From
        public ActionResult IndexStack4()
        {
            if (stackStruct.Count != 0)
            {
                stackStruct.Pop();
                
            }
            else
            {
                ViewBag.Error = "Nothing to delete";

                iCounter = 0;
            }
            ViewBag.Output = stackStruct;

            return View("IndexStack");
        }

        // Clear
        public ActionResult IndexStack5()
        {
            stackStruct.Clear();

            iCounter = 0;

            return View("IndexStack");
        }

        // Search
        public ActionResult IndexStack6()
        {
            Random oRand = new Random();
            int iSearchNum = oRand.Next(1, (iCounter + 1));

            System.Diagnostics.Stopwatch sw = new System.Diagnostics.Stopwatch();

            sw.Start();

            if (stackStruct.Contains(" Item " + iSearchNum + " "))
            {
                ViewBag.SearchResults = stackStruct.ElementAt(iSearchNum - 1);

            }
            else ViewBag.SearchResults = "Not Found";

            sw.Stop();

            TimeSpan ts = sw.Elapsed;

            ViewBag.StopWatch = ts;

            return View("IndexStack");
        }


    }
}

DataStructuresAssignment/Views/Stack/IndexStack.cshtml
<!--Stack Index-->
<!--IS 403 Data Structures Assignment
    Ross Rosenlof, Trevan Reese, Caden Dortch, Ryan Jenks
    This website shows how three data
    structures - stacks, dictionaries, and queues,
    handle data and output them to a view.-->
@{
    ViewBag.Title = "IndexStack";
}

<h2>Stack</h2>
<div class="search-results">
    @if (ViewBag.SearchResults != null)
    {
        <p>The search returned the following result: @ViewBag.SearchResults</p>
        <p>In @ViewBag.StopWatch seconds!</p>
    }
    @if (ViewBag.Error != null)
    {
        <p>@ViewBag.Error</p>
    }
</div>

<div class="vertical-menu column left">
    <a href="@Url.Action("IndexStack1", "Stack")">1. Add one item to Stack</a>
    <a href="@Url.Action("IndexStack2", "Stack")">2. Add Huge List of Items to Stack</a>
    <a href="@Url.Action("IndexStack3", "Stack")">3. Display Stack</a>
    <a href="@Url.Action("IndexStack4", "Stack")">4. Delete from Stack</a>
    <a href="@Url.Action("IndexStack5", "Stack")">5. Clear Stack</a>
    <a href="@Url.Action("IndexStack6", "Stack")">6. Search Stack</a>
    <a href="@Url.Action("Index", "Index")">7. Return to Main Menu</a>
</div>

<div class="display_output column right">

    @if (ViewBag.Output != null)
    {
        <p>
            @foreach (var item in ViewBag.Output)
            {
                @item
            }
        </p>
    }


</div>